### PR TITLE
CloseButtonFunctionnality

### PR DESCRIPTION
**Pull request by mickaelalbertus**
Add a close button to the sidebar.

Imported from Evince project

### CODE REVIEW

**Comment by JosephMcc** [comment]
We removed it: https://github.com/linuxmint/xreader/commit/b0912f3f602c0aeb61742c39a5b366168bbab87f#diff-04b99e8643d1ad9b556c26b580d6e6cc

**Comment by mickaelalbertus** [comment]
Ah ok I didn't know. I found it really useful however :)

**Comment by clefebvre** [comment]
@JosephMcc Are we definitely removing these then? I find it useful as well.. although it does look like an eye-sore.

**Comment by clefebvre** [comment]
@mickaelalbertus can you rebase (that will include .circleci and trigger a CI check), and fix your indentation? We can get this merged then.

**Comment by mickaelalbertus** [comment]
Done! Sorry for the indentation, I never know if I've to use tabulation or space in files.

**Comment by clefebvre** [comment]
Looks good.

@mickaelalbertus there are loads of great editors out there, many of them free software too. Despite not being free, many of us use sublime-text though, so that's what we're used to. In Sublime, you can simply CTRL+A to select all the text and see if blanks are tabs or spaces. You can also install plugins such as gitcutter to highlight modified/added lines in the margin, trailingspaces to highlight trailing spaces in bright pink (that helped me a lot to stop leaving trailing spaces behind in my commits)..etc.

Whichever editor you decide to use, pick one you enjoy and make sure it highlights trailing spaces, git status, spaces/tabs and lets you define your indentation easily.

Anyway, thanks for this PR, it's ready to be merged and sorry it's taking so long to merge the other ones... we had the 18.3 release, then we worked on CI and documentation quite a bit, and we've a backlog of PRs now :)

**Pull request merged**
