### PR TITLE
[Feature request] Please provide "Save" option

### PR DESCRIPTION
**Pull request by mickaelalbertus**
- Add the feature "Save" when the software is closed
- Fix the following behavior: when the user wants to close xrader and a modification was made he can save or save as a copy but once this document is saved (he does not cancel the operation) xreader should be closed but it was not the case.

IssueID#345

### CODE REVIEW

**Comment by JosephMcc** [comment]
I don't think you should be updating the translations this way. That is handled by on our side and all the translations are handled on Launchpad.

**Comment by mickaelalbertus** [comment]
Ok I didn't know, I cancel this modification

**Comment by mickaelalbertus** [comment]
This commit repairs also #275

**Comment by mtwebster** [comment]
It would probably make sense to also have this in the file menu.

**Pull request merged**
