### PR TITLE
Fix for #95 "selecting text does not work"

### LINKED ISSUE #95: selecting text does not work.
Can't select text whith the mouse in pdf documents, specially when the window is maximized. when not, it works better. Crtl-A works for me.
I'm using Linux Mint 18.1 XFCE.
This feature in evince works well with the same documents.

### PR DESCRIPTION
**Pull request by Piiit**
Fixes #95

Works with PDF files already, but needs some additional work to provide the same functionality for all backends. For the latter, I think another PR is better, because it seems to be much more work, and they still work as before for scale = 1.

**UPDATE** It turns out, that the fix for other backends isn't that complicated overall. The new PR should work for all file types.

### CODE REVIEW

**Comment by Piiit** [comment]
@clefebvre I think it is ready to be merged. For other file formats, we can open another PR...

**Comment by Piiit** [comment]
@clefebvre Found an easy fix for other file types. I tested with pdf and djvu so far.

**Comment by mpetroff** [comment]
I've tested this for PDF files, and it fixes the basic text select case. However, it causes problems with scrolling (which is what worked before). When I scroll, the text selection flickers and usually stops being displayed when the scrolling stops. Additionally, this appears to introduce significant performance issues while scrolling.

**Comment by Piiit** [comment]
@mpetroff 
Thanks for your review. I look at it asap. Does it flicker with hidpi only, or with all configurations? Do you have an idea where the performance issue comes from?

**Comment by mpetroff** [comment]
I just tested the patch on another machine that isn't hi-DPI, and I don't see either issue, so it seems to be hi-DPI related.

I'm not sure where the performance issue is coming from, but, based on the flicker, I'd guess that it's trying to render things multiple times. I never really figured out how the draw loop works when I had previously looked into this issue, so I'm not really sure where the issue might be.

**Comment by mpetroff** [comment]
The issue also seems to be document-dependent; it turns out that this is also the case prior to the patch. For example, [this PDF](https://cab.inta-csic.es/users/jrpardo/paper24.pdf) does not exhibit any issues with the patch applied but also had the highlighting remain in the wrong location while scrolling before the patch was applied (the location was correct after switching to a different window, though). On the other hand, every pdfTeX-produced document I've tested, e.g., [this PDF from arXiv](https://arxiv.org/pdf/1808.00820.pdf), show the flickering and performance issues on hi-DPI displays with the patch applied but had the highlighting shown in the correct location while scrolling before the patch was applied.

**Comment by Piiit** [comment]
@mpetroff I backported all performance related selection commits, that I could find. I cannot reproduce the performance and flickering issues anymore. In addition, I added also some other commits that draw a larger damage region for selections and dues reduce redraws. Finally, I found also some list append LOC which do a full list scan and append to a final pointer, prepend is much faster. Please re-test...

**Comment by mpetroff** [comment]
The flicker is gone, and the performance is now much better. There does seem to still be a slight amount of increased lag while scrolling with text selected, but it's at the level that I probably wouldn't notice if I weren't looking for it.

I did however notice that the documents that previously had the flicker issue also have the positions of text shift slightly when it's selected (I checked that this was also true before the most recent commits). Once the view is scrolled or a different window is switched to, the text returns to its original location.

Before scrolling:
select_before_scroll

After scrolling:
select_after_scroll

It's a minor issue, and I don't think that it should hold up merging this pull request. It looks to me to be a slight difference in text hinting, where the before scrolling version looks to be better. Since the text all looks slightly fuzzy before selection, it suggests that it's a separate issue with text hinting (which may very well be my fault, since I wrote the pull request for hi-DPI page rendering). I can open a separate issue to track this, if you agree with my assessment.

**Comment by Piiit** [comment]
@mpetroff I agree on your last comment. Please open a new issue for the hinting issue

**Pull request merged**
