### PR TITLE
Bug fix + Trailing space fix

### PR DESCRIPTION
**Pull request by mickaelalbertus**
Fix bug #175

### CODE REVIEW

**Comment by JosephMcc** [comment]
Please explain what this does as part of your actual commit message.

**Comment by mickaelalbertus** [comment]
It fixes the bug #175: when an user selected View/Page width fit and changed the page with the "Content" view into side pane, it changed the view mode. Now, after changing the page with the side pane, the view mode doesn't change.

**Comment by NikoKrause** [comment]
@mickaelalbertus This commit causes xreader to crash with some pdf files. See https://github.com/linuxmint/xreader/issues/227

**Comment by mickaelalbertus** [comment]
Thanks for reporting this bug! It's corrected now :)

**Pull request merged**
