### PR TITLE
Display number of occurrences in searchbar over whole document

### PR DESCRIPTION
**Pull request by m8**
Hello there,
I needed the feature in #455  very much, too. A large part of it was already done in the previous code. I just added a variable named total_count and tried to show it right next to the result in searches. It could be a nice feature. 
xreader

### CODE REVIEW

**Comment by mtwebster** [comment]
Hi, it works fine, but there are a few issues:

- Please don't update the .po files, we do that with the makepot script at release time, and upload the new potfil to launchpad for translations.  So, the only files to be changed here should be ev-jobs.* and ev-window.c.
- We should continue using the ngettext format (some languages will have singular/plural forms for this, even though the strings here are the same. Also, total is probably better by itself:
```
            message = g_strdup_printf (ngettext ("%d found on this page (%d total)",
                             "%d found on this page (%d total)",
                             n_results),
                             n_results, job_find->total_count);
```

So you get:
image

Thanks!

**Comment by m8** [comment]
@mtwebster thanks for your feedback, i updated the pr according to.

**Comment by mtwebster** [comment]
Hi, looks good except we'll update the potfile as part of our release process, can you remove that change?

**Comment by m8** [comment]
@mtwebster thanks for your feedback, I revert the potfile changes

**Pull request merged**
