### PR TITLE
Meson:  Formatting fix in the options file

### PR DESCRIPTION
**Pull request by Soapux**

### CODE REVIEW

**Comment by collinss** [comment]
Hi @Soapux , thanks for contributing! Could you please give a justification for why this is needed? Generally we try to avoid tab characters unless we absolutely need them (because they display differently depending on the app that's reading them). See https://linuxmint-developer-guide.readthedocs.io/en/latest/guidelines.html#indentation for more information.

**Comment by Soapux** [comment]
Hello, about the justification, I just saw that the formatting of the file was inconsistent and the other options are all tab spaced.  So I just thought I'd make it consistent.  I could change everything to spaces if you prefer.

**Comment by collinss** [comment]
Ah, ok, yeah spaces would be best. Looks like someone (read "me") accidentally used tabs on some of them, and the editor I was using didn't catch it (probably copy/paste from someone else's bad code ;) ). Thanks @Soapux !

**Comment by Soapux** [comment]
Hopefully I did this correctly, let me know if I messed up.  Thanks.

**Comment by collinss** [comment]
lgtm

**Pull request merged**
