### PR TITLE
[WIP] Add annotation improvement

### PR DESCRIPTION
**Pull request by mickaelalbertus**
Concerns issue #163 

- Add a toolbar to add annotation (highlight, underline, strike out and
squiggly) and manage colors of annotations ;
- Fix the minimim width of sidebar to 220px to display all buttons ;
- Change icon of annotation in the tree view of annotation sidebar ;
- Allow to remove and annote all annotations (execute sudo make install
for the changes of pdf backends).

Maybe I should change the tooltips of buttons?

A screenshot: 
capture du 2018-04-21 22-58-21

Edit: majority of code was imported from Evince project.

### CODE REVIEW

**Comment by JosephMcc** [comment]
Ok.So I did a quick review of this. It seems to be working but a few things could use improvements.

1. Please clean up the new build warnings you introduced. Just help avoid potential errors.

2. Use symbolic icons. We have moved to using them wherever possible and I'd like to see them used here.

3. The minimum width you set on the sidebar isn't sufficient. Test this under multiple themes. Adwaita is a good test case because it uses larger padding than most themes. If it works there you can be fairly confident it works in others.

4. There are a lot of runtime warnings when you add a new annotation. Not sure if these are due to your new code or already existed. If they are coming from your PR they should get cleaned up.

**Comment by mickaelalbertus** [comment]
I've solved compilation warnings, indentation in some files and change icon loading code.
I don't find why there are some runtime warnings. I've tried to comment every line of code containing gdk_window_get_origin and it didn't work so I think it's not a bug from this project maybe?

**Comment by clefebvre** [comment]
The build issue with LMDE3 is due to a meson issue in Nemo.

**Comment by mickaelalbertus** [comment]
I implement straight lines and circles annotation. I will add after that some improvements:

- The cursor for the straight line annotations should be only for the line. But poppler doesn't implement the getters for vertices for straight line annotations :(
- The properties window for circle annotation should have an option to change the inside color. And the properties window for both annotation should have an option to change the width, but it doesn't seem to be implemented in poppler.
- I don't know yet if I should add buttons to add circle and line annotations.

**Comment by clefebvre** [comment]
I've a few issues with annotations. It looks pretty cool but I don't think it's polished enough.

- Right-clicking the annotation in the sidebar should allow you to remove it and show its properties
- There must be niche cases here and there, I had xreader freeze when adding annotations, and segfault when removing two text annotations after adding other ones
- The annotations in the sidebar don't refresh when annotations are added (i.e. new annotations appear in the document but not in the sidebar)
- Icons should be symbolic
- "Change color" isn't really explicit... it underlines (in fact it does it better than the straight underline, which is a little too thin)
- Considering annotations can be removed, it's a pity we can't just "save" the document. Why do we need to save a copy instead?
- The min side for the sidebar isn't large enough. The buttons are invisible at min-size with mint-y.

**Comment by mickaelalbertus** [comment]
- For the right-clicking I totally agree, I will add this functionality as soon as possible. It's not supported by evince so it will take some time to write this code ;
- When I add annotation, the sidebar is refreshed and I don't have any troubles when I remove annotations. Did you do make sudo install? Because the backends are modified so it's necessary. If you did, can you send me a pdf example?
- Icons are now symbolic in the commit d3cacb1?
- I don't understand the change color isn't explicit? Do you mean that we should put it in another way? Tooltip isn't enough? The color affects every annotation type.
- I totally agree with the copy save. I thought it was an old functionality useful when the removing annotation wasn't implemented. Do I change that?
- For the min size of sidebar, I will test with other themes. I wanted to make a show arrow but I don't know yet how to write it. I think it should be better than fixing a minimum width. What do you think.

And for now I'm writing a new functionality for djvu backend. I want to implement annotation in djvu document. I think I could do it (I test it a little and it works) but I need to call djvused, a program which extract and add annotation. Do you think thazt the packages could be installed by default in Linux Mint distros? The package is djvulibre-bin.

**Comment by clefebvre** [comment]
Hi Mickael,

You can depend on djvulibre-bin in debian/control.

For the sidebar size, rather than an arbitrary minimum size, we should make sure the buttonbox doesn't let the sidebar get to small. It's probably a property, or we could probably do it by changing its container widget.

For the saving, yes, I think it would be better if we could save and save_as, like in other applications. It's really weird to be unable to save and to have to necessarily duplicate. It might be better to do this in its own PR.

For the build, I always test with dpkg-buildpackage. That's how the package is built.

The "change color" is the tooltip on the wave-underline button, it's misplaced.

In my opinion, we don't really need two underline buttons... we've got a single underline button (which produces lines which look way too thin) and a wave underline button. I'd suggest to keep the wave one only, or to replace both with a thick underline button:

image

**Comment by mickaelalbertus** [comment]
What do you suggest for the add annotations buttons?
I'm still working on djvu annotations and it works very well! But some kind of annotations doesn't work like underline, strikeout or wave annotations. So do we add every annotation buttons? In the property dialog, do we suggest to change the kind of annotation for pdf and disable it for the djvu document?

**Comment by NikoKrause** [comment]
@mickaelalbertus Any plans for getting this done for Mint 19.1?

**Comment by mickaelalbertus** [comment]
Sure, I'm reinstalling all my software (because I change for LMDE3) and I will modify the code. The idea of @voxspox in thread #253 is a good idea. I think I will add two GtkToolPalette (cf [GtkToolPalette](https://developer.gnome.org/gtk3/stable/GtkToolPalette.html)) in the annotations sidebar for the two kind of annotations: when you highlight text and when you add annotation. What do you think about it?

**Comment by Piiit** [comment]
@mickaelalbertus +1 for GtkToolPalette... 
I'd like to see something similar the adober reader sidepane for annotations in the long run... 

image

What do you think?

**Comment by mickaelalbertus** [comment]
I really like this interface. However, GtkToolPalette only supports GtkToolItem so I can't use a aplette for the annotation list but I can use it after the list. I have problem for the size of GtkToolPalette in a hbox because I can't set the palette totally on the bottom of the sidebar, it displays only the button of the palette and not the group of buttons. I'll try to fix it soonly but if you have some advices ;)

**Comment by mickaelalbertus** [comment]
I can't use a GtkToolPalette because of the size and because I can't add a TreeView inside. However, I suggest this presentation:
image

Say me what you think about it? I think to add a button to draw circle and rectangle annotation to be complete.

**Comment by mickaelalbertus** [comment]
Even if I add other buttons like stamp annotations or circle annotations? Should I create only one category?

**Comment by NikoKrause** [comment]
Hmmm... not sure. @JosephMcc any suggestions?

**Comment by Piiit** [comment]
@mickaelalbertus I would go with a single category at the moment, and add categories later on if we need a better overview due to too many annotation types. However, that seems to be a future problem, nothing to worry about for now. Do you have time to continue with this PR?

**Comment by mickaelalbertus** [comment]
@Piiit I just saw your last message and your last pull request. Sorry for the response time. I don't have the time (I finish my thesis) to complete this pull request but I'll continue with yours when I'll have time I do that (annotation for epub file would be a cool functionality).

**Comment by clefebvre** [comment]
Superseded by https://github.com/linuxmint/xreader/pull/324.

**Pull request closed without merging**
