### PR TITLE
Fixing BUG #7: Presentation and Zoom buttons greyed out, if no document has been loaded.

### PR DESCRIPTION
**Pull request by Piiit**
This patch makes zoomin/out and presentation buttons inactive in the menue,
the regular toolbar, and the fullscreen toolbar, if no document has been loaded yet.

### CODE REVIEW

**Comment by clefebvre** [comment]
Thanks @Piiit 

Please:

- Focus solely on the fix (for instance, here, only implement the button sensitivity PR, don't mix in indentation fixes or anything not related directly with the PR).
- Merge your commits into one.

**Comment by Piiit** [comment]
Hi @clefebvre, hopefully this patch is correct now...

Removed all trailing whitespace line changes, and merged things into a single commit...

**Comment by Piiit** [comment]
What about atril? Do you take care of merging if this PR is accepted?

**Comment by clefebvre** [comment]
Thanks @Piiit, for Atril it depends.

I usually annoy @monsta in the hope he'll do it for me, and after he refuses or finds a good excuse I usually end up doing it myself. I also usually end up with more work after I talk to him :)

That said, one of the reason we started Xapps was precisely not to waste time in maintaining DE-specific apps, so I'm not sure I'll be active on MATE apps going forward.

If you can make the same PR for Atril, don't hesitate to do so.

**Comment by Piiit** [comment]
Sorry guys, I messed up my git, thought I am on a branch... now everything is messed up, will fix it as soon as possible.

**Comment by clefebvre** [comment]
Thanks @Piiit no problem at all.

**Pull request closed without merging**
