### PR TITLE
readd short keys for "best fit", "fit page width" and "dual"

### PR DESCRIPTION
**Pull request by voxspox**
https://github.com/linuxmint/xreader/issues/30

@fernando: ok, I tried something. Maybe further changes are necessary. docs?

### CODE REVIEW

**Comment by clefebvre** [comment]
Cool. Can you modify your PR description :)

**Comment by voxspox** [comment]
PR?

**Comment by clefebvre** [comment]
Oh sorry, I meant your Pull Request.

**Comment by voxspox** [comment]
PR, yes of course ;)
I'm pondering about the description...

**Comment by clefebvre** [comment]
It's hard to see on github. It's not really the PR I was worried about, because I can click on #30 and see what it's about. It was the commit message. Usually we put a short description on the first line, and then explain a bit more below. You can then see that info when looking at the git commit.

I wrongly assumed that info was: 

"#30

@fernando: ok, I tried something. Maybe further changes are necessary. docs?"

Github usually shows it as the first comment :)

Sorry about the confusion.

**Comment by anandrkris** [comment]
@clefebvre - I guess we need to update these shortcuts to  **Help > Shortcuts** documentation as well.

https://github.com/linuxmint/xreader/blob/7173bc0076e25b6b5446b58b7a57f34b462cf2c3/help/C/index.docbook

`<row valign="middle">               
            <entry><para><keycap>f</keycap></para></entry>
            <entry><para>Best Fit</para></entry>
</row>`

**Comment by clefebvre** [comment]
We're working on a project in parallel to xreader which consists of rewriting the UI and thumbnailer from scratch, in Python, using the Evince backend and ditching everything else.

Let's wait until we see how far this goes before working on the help.

**Comment by anandrkris** [comment]
Okies, cool. :+1:  for new UI

**Comment by NikoKrause** [comment]
When I read this PR a few days before, I thought there was a d to much. The title made no sense to me at all. Now I read it again. It means "re-add short keys" not "read short keys" :D

**Comment by Piiit** [comment]
@voxspox Hi, this PR breaks search (see #61)... Do you have time to fix that?

**Comment by voxspox** [comment]
@Piiit: sorry, I'm not familiar enough with the code to solve this. How does search work in evince? The zoom hotkeys are available there!

**Pull request merged**
