### PR TITLE
Change border of pages to a realistic shadow, make thumbnails styleable via CSS 

### PR DESCRIPTION
**Pull request by Piiit**

### CODE REVIEW

**Comment by Piiit** [comment]
@clefebvre Done. Please test and merge :-)

**Comment by Piiit** [comment]
@JosephMcc found some compatibility issues regarding GTK 3.22 CSS handling, which need to be fixed first. Back to WIP...

**Comment by Piiit** [comment]
This is a better solution now. I fixed also the css issues. Please re-test...

**Comment by JosephMcc** [comment]
@Piiit I tested this again. It looks ok except the thumbnails in the recents view no longer get a border drawn around them. That needs to be fixed.

**Comment by clefebvre** [comment]
@Piiit @JosephMcc I'll merge this, I think it's a great improvement over master already. Recent thumbs could do with a border, but even now they look better than in master.

PS: The CSS refers to a PNG for the thumb frame, is that OK in HiDPI? Would it look cleaner if it was just 100% CSS, without the need for any image at all? (i.e. a clean border, as opposed to something that's trying to look like a page).

**Pull request merged**
