### PR TITLE
Add remove annotation functionnality

### PR DESCRIPTION
**Pull request by mickaelalbertus**
Add an action for popumenu to remove an annotation

### CODE REVIEW

**Comment by brownsr** [comment]
Sorry, this question seems so dumb, but how do you use this new functionality ?  If I build it then everything seems identical to previous, from a user perspective.  Are there configuration settings that have to be changed to see it, for example ?

**Comment by mickaelalbertus** [comment]
If everything works, you just have to right click on an annotation and you could remove the annotation. It is an option that doesn't exist on xreader if I'm not mistaken.

**Comment by Piiit** [comment]
@mickaelalbertus Hi, nice feature, but could you please remove the i18n (*.po) commit. Translation are handled separately.

**Comment by clefebvre** [comment]
Hi @mickaelalbertus, please rebase this one as well.

**Comment by mickaelalbertus** [comment]
Done!

**Comment by clefebvre** [comment]
Thanks @mickaelalbertus,

This is pretty good. I can't believe this feature wasn't in here before. I've never really looked at annotations before, it's not great...

- The + button to add annotations is a toggle button, it stays toggled after adding an annotation. It would work better as a normal button.
- The + button to add annotations isn't obvious and it's part of something optional (the sidebar). We should probably add an option to add an annotation in the Edit menu, and in the document context menu.
- The + button should probably removed once we add menu options... seeing a + button in a table makes people wonder where the - button is.
- The mouse cursor changes to a + icon when adding an annotation. It's a bit confusing because it makes you believe you should select text, whereas what you're expected to do is simply point and click at a location in the document.
- The sidebar only shows annotations, not their content.. and per page. That's not very handy.
- In the annotations prefs dialog, apply closes the dialog.

While testing the PR, I bumped into something which makes Xreader crash when you remove an annotation. I couldn't find a test case to reproduce this ALWAYS though. Maybe the stack trace will prove useful:

[StackTrace.txt](https://github.com/linuxmint/xreader/files/1594373/StackTrace.txt)

**Comment by clefebvre** [comment]
To reproduce the crash, you need the sidebar visible and showing annotations, and them remove annotations until it crashes :)

**Comment by mickaelalbertus** [comment]
It's really strange. I didn't have this kind of bug when I wrote this code. Now the bus always happens.
When the signal is activated, this bug appears when I change the variable view->window_children (if I assign NULL to it or if I try to remove one element of the GList...).
I'll try to fix it but this is weird!

**Comment by clefebvre** [comment]
Check my merge, it's possible I missed something when merging. I resolved conflicts in ev-view.c if I remember well.

**Pull request merged**
