### PR TITLE
Fix the bug #165: allow to save the epub document.

### PR DESCRIPTION
**Pull request by mickaelalbertus**
Fix the bug #165: allow to save the epub document.

### CODE REVIEW

**Comment by clefebvre** [comment]
hi @mickaelalbertus, you've indentation issues in this PR.

**Comment by mickaelalbertus** [comment]
Done!

**Comment by clefebvre** [comment]
I still see indentation issues.. as much as I hate tabs, you should follow the existing indentation (which is to use tabs for the most part). You also have a function with mixed indentation and wrongly indented code, visible in the diff here.

**Comment by mickaelalbertus** [comment]
Done :)

**Pull request merged**
