### PR TITLE
xreader crash on epub search - reproducable

### PR DESCRIPTION
**Pull request by mickaelalbertus**
BugFix #398

### CODE REVIEW

**Comment by mtwebster** [comment]
Thanks

Interestingly, I discovered another crash while incorrectly following your directions to reproduce.

Try opening the file as a zip with xreader.

**Comment by mickaelalbertus** [comment]
I don't understand. Open the file with the extension zip? What is it observed and expected?

**Comment by mtwebster** [comment]
At first I attempted to open your attached file without renaming it.  It segfaults while loading it.

Obviously this isn't something that people do every day but it shouldn't crash.

(this is unrelated to your fix, just noticed it while testing)

**Comment by mickaelalbertus** [comment]
Ok I reproduced it. I will investigate it!

**Pull request merged**
