### PR TITLE
[wip] Add a EPUB thumbnailer

### PR DESCRIPTION
**Pull request by Piiit**
**TO DO**
- [ ] Make it compilable with epub disabled
- [ ] Exit gracefully if epub is disabled
- [ ] Test nemo integration

### CODE REVIEW

**Comment by clefebvre** [comment]
(nemo:31826): CinnamonDesktop-WARNING **: 12:24:46.905: Unable to create loader for mime type application/epub+zip: Format d'image non reconnu

Picture format not recognized?

**Comment by clefebvre** [comment]
Tested with https://github.com/IDPF/epub3-samples/releases/download/20170606/childrens-literature.epub and nemo.

**Comment by Piiit** [comment]
@clefebvre It works here, I think that error could be something inside nemo?

My command is: `xreader-thumbnailer -s 1000 childrens-literature.epub output.png`

**Comment by Piiit** [comment]
backend/meson.build shows the following
```
if get_option('epub')
    subdir('epub')
    xreader_mime_types += 'application/epub+zip;'
endif
```
It should work for that mimetype. Could it be that another thumbnailer does not recognize that mimetype correctly?

**Comment by clefebvre** [comment]
Superseded by https://github.com/linuxmint/xapp-thumbnailers

**Pull request closed without merging**
