### PR TITLE
Evince Backport:  Allow adding Highlight annotations from text selection

### PR DESCRIPTION
**Pull request by m8**
It is really practical to be able to add it as highlight after selecting the text. Constantly, it's hard to add from the menu. I backported it from Evince. Might be a good PR if you can test it.

Backported by Musa Unal

Taken from:
[1] https://gitlab.gnome.org/GNOME/evince/-/commit/fc0d21167185b34955f4996b35b0c479e0d482f3
[2] https://gitlab.gnome.org/GNOME/evince/-/merge_requests/198/diffs?commit_id=07d0461045be13bccf13b1145c266e7e61bb75e8

[1] commit fc0d21167185b34955f4996b35b0c479e0d482f3
[2] commit 07d0461045be13bccf13b1145c266e7e61bb75e8
Author:  Nelson Benitez 

```
As this is a natural, intuitive way to add text markup
annotations to a document.

The "Highlight Selected Text" action
in the context menu
will show if there is a selection. When
the selection spreads over several pages,
one annotation per page will be added accordingly
to fulfill the user expectation of all selected text
to be annotated.

https://bugzilla.gnome.org/show_bug.cgi?id=763943
```

### CODE REVIEW

**Comment by m8** [comment]
I noticed that there are some bugs in the annotation locations when it is saved. I am working on it.

**Comment by sidmint** [comment]
just mentioning that, apart from context menu facility, directly pressing ctrl H and alt H works too, in evince and deepin reader respectively.

**Comment by tyagi-ankit** [comment]
Hi, this feature is still not there, right?

**Comment by sidmint** [comment]
#547 similar request.
This basic feature is still missing and manual option of adding highlight/annotate is very unintuitive to find.
Evince got this long ago, new epub reader to be launched which is mentioned in blog has it from day one.

**Pull request merged**
