### PR TITLE
Toolbar revamp

### PR DESCRIPTION
**Pull request by JosephMcc**

### CODE REVIEW

**Comment by Piiit** [comment]
@JosephMcc I tested this patch and I think it should not be applied! It removes the ability to personalize the toolbar... I like to have many buttons on my toolbar to access functions easily. This patch removes power-user functionality... I suggest to keep EggEditable toolbar... this gnomifies xreader IMO.

**Comment by JosephMcc** [comment]
> this gnomifies xreader IMO.

Hardly. It's not like we're removing menus, using header bars and popovers, etc. EggEditableToolbar is already removed in other apps like Xviewer. This makes it consistent with other Xapps like XViewer and Xed. It also means it will work properly for users who use dark and partially dark gtk themes regardless of the icon sets they use.

**Comment by Piiit** [comment]
@JosephMcc How do we integrate the back-button for large document navigation with linked sections? I think that the "back-button" is not accessible through the menu at all. See #100 ...

**Comment by JosephMcc** [comment]
It should definitely be made available from the menu. That should probably happen regardless of toolbar changes. Imho, no functionality should be hidden that way.

**Comment by clefebvre** [comment]
I fully agree with @JosephMcc on this. I suppose simple toolbars which work well and are easy to maintain.

If functionality is found missing in the menu or even the toolbar, it should be added after this PR is merged. I'll leave it open a little so you can continue to discuss.

**Comment by Piiit** [comment]
@JosephMcc @clefebvre What do you think about the KDE way of creating personalized toolbars? 
Maybe this could be added into a configuration dialog or something... adding it to all xapps... 
It is not the best design IMO, but could be a start...

configure toolbars okular_058

**Comment by JosephMcc** [comment]
Honestly, I think that's massive overkill. I'm all for tweaking what gets shown in the toolbar. If there are options that are often used that aren't there in the old default one. I'd also be curious to know what other options aren't exposed like the back button functionality in the menu.

**Comment by clefebvre** [comment]
Same here, it's really overkill imo.

**Pull request merged**
